data_paths:
  raw_data_path: "${PROJECT_ROOT}/data/raw/"
  feature_store_path: "${PROJECT_ROOT}/data/feature_store/"
  model_store_path: "${PROJECT_ROOT}/models/churn/"

business_logic:
  churn_horizon_days: 30
  feature_window_days: 90
  minimum_tenure_days: 60

modeling:
  temporal_split_date: "2024-09-01"
  train_ratio: 0.7

performance_thresholds:
  min_auc_threshold: 0.75
  min_precision_threshold: 0.2
  target_recall: 0.1

processing:
  shap_sample_size: 1000